import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  FileText, Download, Eye, Calendar, BarChart3,
  Filter, Search, FileIcon, Trash2, X
} from 'lucide-react'
import GlassCard from '../components/ui/GlassCard'
import NeonButton from '../components/ui/NeonButton'
import SeverityBadge from '../components/ui/SeverityBadge'

const mockReports = [
  { id: 'RPT-001', title: 'Highway NH-48 Survey Analysis', type: 'mapping', date: '2025-01-15', objects: 342, status: 'ready', format: 'PDF' },
  { id: 'RPT-002', title: 'Flood Damage Assessment - Sector 4', type: 'disaster', date: '2025-01-14', objects: 23, status: 'ready', severity: 5, format: 'PDF' },
  { id: 'RPT-003', title: 'Industrial Zone Mapping', type: 'mapping', date: '2025-01-13', objects: 156, status: 'ready', format: 'DOCX' },
  { id: 'RPT-004', title: 'Park Vegetation Health Report', type: 'mapping', date: '2025-01-12', objects: 89, status: 'generating', format: 'PDF' },
  { id: 'RPT-005', title: 'Traffic Congestion Analysis - Ring Road', type: 'mapping', date: '2025-01-11', objects: 890, status: 'ready', format: 'Excel' },
  { id: 'RPT-006', title: 'Fire Incident Assessment - Block C', type: 'disaster', date: '2025-01-10', objects: 15, status: 'ready', severity: 4, format: 'PDF' },
]

export default function ReportsPage() {
  const [reports, setReports] = useState(() => {
    const saved = localStorage.getItem('skyrecon_reports')
    return saved ? JSON.parse(saved) : mockReports
  })
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedReport, setSelectedReport] = useState(null)
  const [activeFilter, setActiveFilter] = useState('all') // 'all' | 'mapping' | 'disaster' | 'ready' | 'generating'
  const [showFilterMenu, setShowFilterMenu] = useState(false)

  const handleDeleteReport = (id) => {
    const updated = reports.filter(r => r.id !== id)
    setReports(updated)
    localStorage.setItem('skyrecon_reports', JSON.stringify(updated))
  }

  const handleDownloadReport = (report) => {
    if (report.status !== 'ready') return
    const content = `SKYRECON PLATFORM REPORT - ${report.id}
==============================================
Title: ${report.title}
Date: ${report.date}
Analysis Type: ${report.type.toUpperCase()}
Total Detected Objects: ${report.objects}
Status: ${report.status.toUpperCase()}
Format: ${report.format}
==============================================
Description: Detailed drone analysis output.
This report is generated by SkyRecon AI Drone Platform.
For detailed video overlays and GIS mapping, log in to the dashboard.`

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${report.id}_report.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const filteredReports = reports.filter(report => {
    const matchesSearch =
      report.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      report.id.toLowerCase().includes(searchQuery.toLowerCase())
    const matchesFilter =
      activeFilter === 'all' ||
      report.type === activeFilter ||
      report.status === activeFilter
    return matchesSearch && matchesFilter
  })

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold mb-1">Reports</h1>
          <p className="text-sm text-[var(--text-muted)]">View and download analysis reports</p>
        </div>
        <div className="flex items-center gap-3">
          {/* Search — use inline style to guarantee left padding overrides global glass-input */}
          <div className="relative">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)] pointer-events-none z-10" />
            <input
              type="text"
              placeholder="Search reports..."
              className="glass-input text-sm w-48"
              style={{ paddingLeft: '2.25rem', paddingRight: '1rem', paddingTop: '0.5rem', paddingBottom: '0.5rem' }}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>

          {/* Filter button with dropdown */}
          <div className="relative">
            <button
              onClick={() => setShowFilterMenu(prev => !prev)}
              className={`flex items-center gap-2 px-3 py-2 rounded-xl border text-xs font-medium transition-all cursor-pointer ${
                activeFilter !== 'all'
                  ? 'bg-green-500/10 text-green-400 border-green-500/30'
                  : 'bg-white/[0.03] text-[var(--text-secondary)] border-white/10 hover:border-white/20 hover:text-white'
              }`}
            >
              <Filter size={13} />
              {activeFilter === 'all' ? 'Filter' : activeFilter.charAt(0).toUpperCase() + activeFilter.slice(1)}
            </button>

            <AnimatePresence>
              {showFilterMenu && (
                <>
                  <div className="fixed inset-0 z-40" onClick={() => setShowFilterMenu(false)} />
                  <motion.div
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: 6 }}
                    className="absolute right-0 mt-2 w-44 bg-[#0b0f19] border border-green-500/20 rounded-xl shadow-2xl z-50 overflow-hidden"
                  >
                    {[
                      { value: 'all',        label: 'All Reports' },
                      { value: 'mapping',    label: 'Mapping Only' },
                      { value: 'disaster',   label: 'Disaster Only' },
                      { value: 'ready',      label: 'Ready' },
                      { value: 'generating', label: 'Generating' },
                    ].map(opt => (
                      <button
                        key={opt.value}
                        onClick={() => { setActiveFilter(opt.value); setShowFilterMenu(false) }}
                        className={`w-full text-left px-4 py-2.5 text-xs transition-colors cursor-pointer ${
                          activeFilter === opt.value
                            ? 'bg-green-500/10 text-green-400 font-semibold'
                            : 'text-[var(--text-secondary)] hover:bg-white/[0.04] hover:text-white'
                        }`}
                      >
                        {opt.label}
                      </button>
                    ))}
                  </motion.div>
                </>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'Total Reports', value: reports.length, icon: FileText, color: '#22c55e' },
          { label: 'This Month', value: reports.filter(r => r.date.startsWith('2025-01')).length, icon: Calendar, color: '#06b6d4' },
          { label: 'Disaster Reports', value: reports.filter(r => r.type === 'disaster').length, icon: FileIcon, color: '#ef4444' },
          { 
            label: 'Avg Objects/Report', 
            value: reports.length ? Math.round(reports.reduce((acc, r) => acc + r.objects, 0) / reports.length) : 0, 
            icon: BarChart3, 
            color: '#a855f7' 
          },
        ].map((stat, i) => (
          <GlassCard key={stat.label} className="p-4" delay={i * 0.05} hover={false}>
            <div className="flex items-center gap-2 mb-2">
              <stat.icon size={14} style={{ color: stat.color }} />
              <span className="text-xs text-[var(--text-muted)]">{stat.label}</span>
            </div>
            <p className="text-xl font-bold" style={{ color: stat.color }}>{stat.value}</p>
          </GlassCard>
        ))}
      </div>

      {/* Reports List */}
      <GlassCard hover={false}>
        <div className="space-y-2">
          {filteredReports.length === 0 ? (
            <div className="text-center py-12 text-[var(--text-muted)] font-mono text-sm">
              NO REPORTS FOUND FOR THE CURRENT QUERY
            </div>
          ) : (
            filteredReports.map((report, i) => (
              <motion.div
                key={report.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 + i * 0.05 }}
                whileHover={{ x: 4 }}
                className="flex items-center gap-4 p-4 rounded-xl hover:bg-white/[0.02] cursor-pointer transition-all border border-transparent hover:border-white/5"
              >
                {/* Clickable Info Area */}
                <div 
                  className="flex flex-1 items-center gap-4 min-w-0"
                  onClick={() => report.status === 'ready' && setSelectedReport(report)}
                >
                  {/* Icon */}
                  <div className={`
                    w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0
                    ${report.type === 'disaster' ? 'bg-red-500/10 text-red-400' : 'bg-green-500/10 text-green-400'}
                  `}>
                    <FileText size={18} />
                  </div>

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-0.5">
                      <p className="text-sm font-semibold truncate">{report.title}</p>
                      {report.severity && <SeverityBadge level={report.severity} size="sm" showLabel={false} />}
                    </div>
                    <div className="flex items-center gap-3 text-xs text-[var(--text-muted)]">
                      <span className="font-mono">{report.id}</span>
                      <span>{report.date}</span>
                      <span>{report.objects} objects</span>
                    </div>
                  </div>
                </div>

                {/* Format badge */}
                <span className={`
                  px-2.5 py-1 rounded-lg text-xs font-medium
                  ${report.format === 'PDF' ? 'bg-red-500/10 text-red-400' : 
                    report.format === 'DOCX' ? 'bg-blue-500/10 text-blue-400' : 
                    'bg-green-500/10 text-green-400'}
                `}>
                  {report.format}
                </span>

                {/* Status */}
                <span className={`text-xs font-medium ${
                  report.status === 'ready' ? 'text-green-400' : 'text-cyan-400'
                }`}>
                  {report.status === 'generating' ? '⏳ Generating...' : '✓ Ready'}
                </span>

                {/* Actions */}
                <div className="flex items-center gap-1">
                  <NeonButton 
                    variant="ghost" 
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation()
                      if (report.status === 'ready') setSelectedReport(report)
                    }}
                    title="View Report Details"
                    disabled={report.status !== 'ready'}
                    className={report.status !== 'ready' ? 'opacity-40 cursor-not-allowed' : ''}
                  >
                    <Eye size={14} />
                  </NeonButton>
                  <NeonButton 
                    variant="ghost" 
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation()
                      handleDownloadReport(report)
                    }}
                    title="Download Report"
                    disabled={report.status !== 'ready'}
                    className={report.status !== 'ready' ? 'opacity-40 cursor-not-allowed' : ''}
                  >
                    <Download size={14} />
                  </NeonButton>
                  <NeonButton 
                    variant="ghost" 
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation()
                      handleDeleteReport(report.id)
                    }}
                    title="Delete Report"
                    className="text-red-400/70 hover:text-red-400 hover:bg-red-500/10"
                  >
                    <Trash2 size={14} />
                  </NeonButton>
                </div>
              </motion.div>
            ))
          )}
        </div>
      </GlassCard>

      {/* Modal for viewing report */}
      <AnimatePresence>
        {selectedReport && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            {/* Backdrop */}
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-black/60 backdrop-blur-sm"
              onClick={() => setSelectedReport(null)}
            />
            {/* Content card */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className="relative w-full max-w-2xl bg-[#0c1017] border border-green-500/20 shadow-2xl rounded-2xl p-6 z-10 text-left overflow-hidden"
            >
              {/* Accent strip */}
              <div className={`absolute top-0 left-0 right-0 h-1.5 ${
                selectedReport.type === 'disaster' ? 'bg-gradient-to-r from-red-500 to-orange-500' : 'bg-gradient-to-r from-green-500 to-cyan-500'
              }`} />
              
              {/* Header */}
              <div className="flex items-start justify-between mb-6 mt-2">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-mono text-[var(--text-muted)] uppercase tracking-wider">{selectedReport.id}</span>
                    <span className={`px-2 py-0.5 rounded text-[10px] font-mono border ${
                      selectedReport.type === 'disaster' 
                        ? 'bg-red-500/5 text-red-400 border-red-500/10' 
                        : 'bg-green-500/5 text-green-400 border-green-500/10'
                    }`}>
                      {selectedReport.type === 'disaster' ? 'Disaster Response' : 'Mapping & Survey'}
                    </span>
                  </div>
                  <h2 className="text-xl font-bold text-white">{selectedReport.title}</h2>
                </div>
                <button 
                  onClick={() => setSelectedReport(null)}
                  className="p-1 rounded-lg hover:bg-white/5 text-[var(--text-muted)] hover:text-white transition-colors cursor-pointer"
                >
                  <X size={18} />
                </button>
              </div>

              {/* Grid detail metrics */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
                <div className="bg-white/[0.02] border border-white/5 rounded-xl p-3">
                  <p className="text-[10px] font-mono text-[var(--text-muted)] uppercase">Date Created</p>
                  <p className="text-sm font-semibold text-white mt-1">{selectedReport.date}</p>
                </div>
                <div className="bg-white/[0.02] border border-white/5 rounded-xl p-3">
                  <p className="text-[10px] font-mono text-[var(--text-muted)] uppercase">Total Detections</p>
                  <p className="text-sm font-semibold text-white mt-1">{selectedReport.objects} items</p>
                </div>
                <div className="bg-white/[0.02] border border-white/5 rounded-xl p-3">
                  <p className="text-[10px] font-mono text-[var(--text-muted)] uppercase">Format Type</p>
                  <p className="text-sm font-semibold text-white mt-1">{selectedReport.format}</p>
                </div>
                <div className="bg-white/[0.02] border border-white/5 rounded-xl p-3">
                  <p className="text-[10px] font-mono text-[var(--text-muted)] uppercase">Platform Version</p>
                  <p className="text-sm font-semibold text-green-400 mt-1 font-mono">v1.2.0-yolo</p>
                </div>
              </div>

              {/* Simulated Analysis Overview */}
              <div className="space-y-4 mb-6">
                <div>
                  <h4 className="text-xs font-mono text-green-400 uppercase mb-1.5">AI Analysis Summary</h4>
                  <p className="text-sm text-[var(--text-secondary)] leading-relaxed bg-white/[0.01] border border-white/5 p-3.5 rounded-xl">
                    Using the {selectedReport.type === 'disaster' ? 'Disaster Detection Engine' : 'Standard Survey Engine'}, the SkyRecon platform processed high-definition aerial imagery. 
                    A total of {selectedReport.objects} elements were successfully resolved with an average model confidence of 91.2%. 
                    {selectedReport.type === 'disaster' 
                      ? ' High-severity hazards including structural distress, road blockage, and active hot spots were annotated. Priority status was raised for urgent response planning.'
                      : ' Map features, land-use outlines, vegetation canopy indicators, and traffic flows were mapped to the GIS projection coordinates.'
                    }
                  </p>
                </div>

                <div>
                  <h4 className="text-xs font-mono text-cyan-400 uppercase mb-1.5">Detection Breakdown</h4>
                  <div className="grid grid-cols-2 gap-3 text-xs">
                    <div className="flex justify-between p-2 border border-white/5 rounded-lg">
                      <span className="text-[var(--text-muted)]">Vehicles / Drones</span>
                      <span className="font-semibold text-white">{Math.round(selectedReport.objects * 0.4)}</span>
                    </div>
                    <div className="flex justify-between p-2 border border-white/5 rounded-lg">
                      <span className="text-[var(--text-muted)]">Buildings / Infrastructure</span>
                      <span className="font-semibold text-white">{Math.round(selectedReport.objects * 0.25)}</span>
                    </div>
                    <div className="flex justify-between p-2 border border-white/5 rounded-lg">
                      <span className="text-[var(--text-muted)]">Vegetation / Canopies</span>
                      <span className="font-semibold text-white">{Math.round(selectedReport.objects * 0.2)}</span>
                    </div>
                    <div className="flex justify-between p-2 border border-white/5 rounded-lg">
                      <span className="text-[var(--text-muted)]">Others / Unclassified</span>
                      <span className="font-semibold text-white">{Math.round(selectedReport.objects * 0.15)}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Actions Footer */}
              <div className="flex items-center justify-end gap-3 pt-4 border-t border-white/5">
                <button
                  onClick={() => setSelectedReport(null)}
                  className="px-4 py-2 rounded-xl text-xs font-mono text-[var(--text-secondary)] hover:text-white transition-colors cursor-pointer"
                >
                  CLOSE
                </button>
                <NeonButton 
                  variant="primary" 
                  size="sm" 
                  icon={Download}
                  onClick={() => {
                    handleDownloadReport(selectedReport)
                    setSelectedReport(null)
                  }}
                  disabled={selectedReport.status !== 'ready'}
                >
                  Download Analysis
                </NeonButton>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  )
}
